LicenseTool.WebApplication/Controllers/LicenseUsageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LicenseTool.ClassLibrary;
using LicenseTool.WebApplication.Models;

namespace LicenseTool.WebApplication.Controllers
{

    /// <summary>
    /// Controller for the LicenseUsage entity
    /// </summary>
    public class LicenseUsageController : BaseController
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger
            (System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private ILicenseToolContext db = null;

        /// <summary>
        /// Constructor initializing the instance
        /// </summary>
        public LicenseUsageController()
        {
            if (log.IsDebugEnabled) log.Debug("LicenseUsageController");

            this.db = new LicenseToolDatabaseEntities();

            if (log.IsDebugEnabled) log.Debug("LicenseUsageController Done");
        }

        /// <summary>
        /// Constructor initializing the instance
        /// </summary>
        /// <param name="db">The databse context to be used</param>
        public LicenseUsageController(ILicenseToolContext db)
        {
            if (log.IsDebugEnabled) log.Debug("LicenseUsageController");

            this.db = db;

            if (log.IsDebugEnabled) log.Debug("LicenseUsageController Done");
        }

        /// <summary>
        /// Shows the list of all entities and passes it to <see cref="Index(LicenseUsageSearchModel)"/>
        /// </summary>
        /// <param name="licenseId">The id of the License the index has to be filtered</param>
        /// <param name="serverId">The id of the LicServer the index has to be filtered</param>
        /// <param name="hostId">The id of the LicHost the index has to be filtered</param>
        /// <param name="userId">The id of the LicUser the index has to be filtered</param>
        /// <param name="showOutOnly"></param>
        /// <returns>The view result</returns>
        public ActionResult Index(int licenseId = 0, int serverId = 0, int hostId = 0, int userId = 0, bool showOutOnly = false)
        {
            if (log.IsDebugEnabled) log.Debug("Index");

            LicenseUsageSearchModel search = new LicenseUsageSearchModel();
            search.License = licenseId;
            search.SelectedLicServer = serverId;
            search.ShowOutOnly = showOutOnly;
            search.LicHost = hostId;
            search.LicUser = userId;
            search.SortColumn = "StartDate";
            search.SortDirection = 1;
            if (licenseId > 0)
            {
                License lic = db.License.FirstOrDefault(l => l.Id == licenseId);
                if (lic != null) search.SelectedLicServer = lic.LicServer;
            }

            if (log.IsDebugEnabled) log.Debug("Index Done");
            return Index(search);
        }

        /// <summary>
        /// Shows the list of all entities
        /// </summary>
        /// <param name="search">The search model to be applied</param>
        /// <returns>The view result</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LicenseUsageSearchModel search)
        {
            if (log.IsDebugEnabled) log.Debug("Index");

            var licenseusage = db.LicenseUsage.Include(l => l.NavLicense).Include(l => l.NavLicHost).Include(l => l.NavLicUser).Include(l => l.NavLicense.NavLicServer);
            List<LicServer> servers = new List<LicServer>(db.LicServer.OrderBy(s => s.Name));
            IQueryable<LicenseUsage> foundItems = null;
            SelectList lst = new SelectList(servers, "Id", "Name");
            ViewBag.AllLicServers = lst;
            ViewBag.AllStates = Helpers.EnumAsSelectList(typeof(LicenseState));
            if (search.SelectedLicServer == 0)
            {
                List<License> licenses = new List<License>();
                ViewBag.AllLicenses = new SelectList(licenses, "Id", "FeatureName");
                foundItems = licenseusage;
            }
            else
            {
                List<License> licenses = new List<License>(db.License.Where(l => l.LicServer == search.SelectedLicServer).OrderBy(s => s.FeatureName));
                if (search.License == 0)
                {
                    ViewBag.AllLicenses = new SelectList(licenses, "Id", "FeatureName");
                    foundItems = licenseusage.Where(u => u.NavLicense.NavLicServer.Id == search.SelectedLicServer);
                }
                else
                {
                    ViewBag.AllLicenses = new SelectList(licenses, "Id", "FeatureName", search.License);
                    foundItems = licenseusage.Where(u => u.NavLicense.Id == search.License);
                }
            }
            if (search.NavLicense == null && search.License > 0)
                search.NavLicense = db.License.Find(new object[]{ search.License });
            if (search.NavLicUser == null && search.LicUser > 0)
                search.NavLicUser = db.LicUser.Find(new object[] { search.LicUser });
            if (search.NavLicHost == null && search.LicHost > 0)
                search.NavLicHost = db.LicHost.Find(new object[] { search.LicHost });

            if (search.NavLicense != null && !string.IsNullOrEmpty(search.NavLicense.FeatureName))
            {
                string[] tsts = search.NavLicense.FeatureName.ToLower().Trim(new char[] { '*' }).Split(new char[] { '*' });
                foreach (string tst in tsts)
                    foundItems = foundItems.Where(u => u.NavLicense == null || u.NavLicense.FeatureName == null ? false : u.NavLicense.FeatureName.ToLower().Contains(tst));
            }
            if (search.NavLicUser != null && !string.IsNullOrEmpty(search.NavLicUser.Name))
            {
                string[] tsts = search.NavLicUser.Name.ToLower().Trim(new char[] { '*' }).Split(new char[] { '*' });
                foreach (string tst in tsts)
                    foundItems = foundItems.Where(u => u.NavLicUser == null || u.NavLicUser.Name == null ? false : u.NavLicUser.Name.ToLower().Contains(tst));
            }
            if (search.NavLicHost != null && !string.IsNullOrEmpty(search.NavLicHost.Name))
            {
                string[] tsts = search.NavLicHost.Name.ToLower().Trim(new char[] { '*' }).Split(new char[] { '*' });
                foreach (string tst in tsts)
                    foundItems = foundItems.Where(u => u.NavLicHost == null || u.NavLicHost.Name == null ? false : u.NavLicHost.Name.ToLower().Contains(tst));
            }
            if (!string.IsNullOrEmpty(search.Version))
            {
                string[] tsts = search.Version.ToLower().Trim(new char[] { '*' }).Split(new char[] { '*' });
                foreach (string tst in tsts)
                    foundItems = foundItems.Where(l => l.Version.ToLower().Contains(tst));
            }
            if (search.Quantity != null)
            {
                foundItems = foundItems.Where(u => u.Quantity == search.Quantity);
            }
            if (search.State != null)
            {
                foundItems = foundItems.Where(u => u.State == search.State);
            }
            if (search.StartDate != null)
            {
                foundItems = foundItems.Where(u => u.StartDate == search.StartDate);
            }
            if (search.EndDate != null)
            {
                foundItems = foundItems.Where(u => u.EndDate == search.EndDate);
            }
            if (search.ShowOutOnly)
            {
                foundItems = foundItems.Where(u => u.State == (int)LicenseState.OUT);
            }
            search.MaxItems = foundItems.Count();
            search.PageSize = Helpers.GetPageSize();
            foundItems = foundItems.Distinct();
            if (search.SortColumn == "EndDate")
            {
                if (search.SortDirection == 0)
                    foundItems = foundItems.OrderBy(s => s.EndDate);
                else
                    foundItems = foundItems.OrderByDescending(s => s.EndDate);
            }
            if (search.SortColumn == "StartDate")
            {
                if (search.SortDirection == 0)
                    foundItems = foundItems.OrderBy(s => s.StartDate);
                else
                    foundItems = foundItems.OrderByDescending(s => s.StartDate);
            }
            if (search.SortColumn == "State")
            {
                if (search.SortDirection == 0)
                    foundItems = foundItems.OrderBy(s => s.State);
                else
                    foundItems = foundItems.OrderByDescending(s => s.State);
            }
            if (search.SortColumn == "Version")
            {
                if (search.SortDirection == 0)
                    foundItems = foundItems.OrderBy(s => s.Version);
                else
                    foundItems = foundItems.OrderByDescending(s => s.Version);
            }
            if (search.SortColumn == "Quantity")
            {
                if (search.SortDirection == 0)
                    foundItems = foundItems.OrderBy(s => s.Quantity);
                else
                    foundItems = foundItems.OrderByDescending(s => s.Quantity);
            }
            if (search.SortColumn == "NavLicUser.Name")
            {
                if (search.SortDirection == 0)
                    foundItems = foundItems.OrderBy(s => s.NavLicUser.Name);
                else
                    foundItems = foundItems.OrderByDescending(s => s.NavLicUser.Name);
            }
            if (search.SortColumn == "NavLicHost.Name")
            {
                if (search.SortDirection == 0)
                    foundItems = foundItems.OrderBy(s => s.NavLicHost.Name);
                else
                    foundItems = foundItems.OrderByDescending(s => s.NavLicHost.Name);
            }

LicenseTool.WebApplication/Views/LicenseUsage/Create.cshtml
@model LicenseTool.ClassLibrary.LicenseUsage

@{
    ViewBag.Title = @LicenseTool.ResourceLibrary.Common.Create;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><img src="~/Images/usage.png" alt="@ViewBag.Title" />@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>@LicenseTool.ResourceLibrary.Model.LicenseUsage</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.EndDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EndDate)
            @Html.ValidationMessageFor(model => model.EndDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StartDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StartDate)
            @Html.ValidationMessageFor(model => model.StartDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LicUser, "NavLicUser")
        </div>
        <div class="editor-field">
            @Html.DropDownList("LicUser", String.Empty)
            @Html.ValidationMessageFor(model => model.LicUser)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LicHost, "NavLicHost")
        </div>
        <div class="editor-field">
            @Html.DropDownList("LicHost", String.Empty)
            @Html.ValidationMessageFor(model => model.LicHost)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.License, "NavLicense")
        </div>
        <div class="editor-field">
            @Html.DropDownList("License", String.Empty)
            @Html.ValidationMessageFor(model => model.License)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.State)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.State)
            @Html.ValidationMessageFor(model => model.State)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Version)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Version)
            @Html.ValidationMessageFor(model => model.Version)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Quantity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Quantity)
            @Html.ValidationMessageFor(model => model.Quantity)
        </div>

        <p>
            <input type="submit" value="@LicenseTool.ResourceLibrary.Common.Create" />
        </p>
    </fieldset>
}

<div>
    @Html.Partial("~/Views/Shared/BackToList.cshtml")
</div>

@section Scripts {
    @Html.Partial("~/Views/Shared/Validation.cshtml")
}

LicenseTool.WebApplication/Views/LicenseUsage/Delete.cshtml
@model LicenseTool.ClassLibrary.LicenseUsage

@{
    ViewBag.Title = @LicenseTool.ResourceLibrary.Common.Delete;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><img src="~/Images/usage.png" alt="@ViewBag.Title" />@ViewBag.Title</h2>

<h3>@LicenseTool.ResourceLibrary.Common.AreYouSureDelete</h3>
<fieldset>
    <legend>@LicenseTool.ResourceLibrary.Model.LicenseUsage</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EndDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EndDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.StartDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StartDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NavLicUser.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NavLicUser.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NavLicHost.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NavLicHost.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NavLicense.FeatureName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NavLicense.FeatureName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.State)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.State)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Version)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Version)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quantity)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="@LicenseTool.ResourceLibrary.Common.Delete" /> |
        @Html.Partial("~/Views/Shared/BackToList.cshtml")
    </p>
}

LicenseTool.WebApplication/Views/LicenseUsage/Details.cshtml
@model LicenseTool.ClassLibrary.LicenseUsage

@{
    ViewBag.Title = @LicenseTool.ResourceLibrary.Common.Details;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><img src="~/Images/usage.png" alt="@ViewBag.Title" />@ViewBag.Title</h2>

<fieldset>
    <legend>@LicenseTool.ResourceLibrary.Model.LicenseUsage</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EndDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EndDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.StartDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StartDate)
    </div>

    <div class="display-label">
         User @Html.DisplayNameFor(model => model.NavLicUser.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NavLicUser.Name)
    </div>

    <div class="display-label">
         Host @Html.DisplayNameFor(model => model.NavLicHost.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NavLicHost.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NavLicense.FeatureName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NavLicense.FeatureName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.State)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.State)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Version)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Version)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quantity)
    </div>
</fieldset>
<p>
    @Html.ActionLinkWithImage("", "Edit", new { id = Model.Id }, "~/Images/edit.png", LicenseTool.ResourceLibrary.Common.Edit, new { @width = "32", @height = "32", @class = "noprint" })
    @Html.Partial("~/Views/Shared/BackToList.cshtml")
</p>

LicenseTool.WebApplication/Views/LicenseUsage/Edit.cshtml
@model LicenseTool.ClassLibrary.LicenseUsage

@{
    ViewBag.Title = @LicenseTool.ResourceLibrary.Common.Edit;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><img src="~/Images/usage.png" alt="@ViewBag.Title" />@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>@LicenseTool.ResourceLibrary.Model.LicenseUsage</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.EndDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EndDate)
            @Html.ValidationMessageFor(model => model.EndDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StartDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StartDate)
            @Html.ValidationMessageFor(model => model.StartDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LicUser, "NavLicUser")
        </div>
        <div class="editor-field">
            @Html.DropDownList("LicUser", String.Empty)
            @Html.ValidationMessageFor(model => model.LicUser)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LicHost, "NavLicHost")
        </div>
        <div class="editor-field">
            @Html.DropDownList("LicHost", String.Empty)
            @Html.ValidationMessageFor(model => model.LicHost)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.License, "NavLicense")
        </div>
        <div class="editor-field">
            @Html.DropDownList("License", String.Empty)
            @Html.ValidationMessageFor(model => model.License)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.State)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.State)
            @Html.ValidationMessageFor(model => model.State)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Version)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Version)
            @Html.ValidationMessageFor(model => model.Version)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Quantity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Quantity)
            @Html.ValidationMessageFor(model => model.Quantity)
        </div>

        <p>
            <input type="submit" value="@LicenseTool.ResourceLibrary.Common.Save" />
        </p>
    </fieldset>
}

<div>
    @Html.Partial("~/Views/Shared/BackToList.cshtml")
</div>

@section Scripts {
    @Html.Partial("~/Views/Shared/Validation.cshtml")
}

LicenseTool.WebApplication/Views/LicenseUsage/Index.cshtml
@model LicenseTool.WebApplication.Models.LicenseUsageSearchModel

@{
    ViewBag.Title = @LicenseTool.ResourceLibrary.Model.LicenseUsages;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><img src="~/Images/usage.png" alt="@ViewBag.Title" />@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "LicenseUsage"))
{
    @Html.AntiForgeryToken()
    <p>
        @Html.HiddenFor(model => model.PagingStartIndex)
        @Html.HiddenFor(model => model.SortColumn)
        @Html.HiddenFor(model => model.SortDirection)
    </p>
    <p>
    </p>
    <table>
        <tr>
            <th>
                <a onclick="LicToolSortPage('EndDate'); return false;" href="#">@Html.DisplayNameFor(model => model.EndDate)</a>
            </th>
            <th>
                <a onclick="LicToolSortPage('StartDate'); return false;" href="#">@Html.DisplayNameFor(model => model.StartDate)</a>
            </th>
            <th>
                <a onclick="LicToolSortPage('NavLicUser.Name'); return false;" href="#">User @Html.DisplayNameFor(model => model.NavLicUser.Name)</a>
            </th>
            <th>
                <a onclick="LicToolSortPage('NavLicHost.Name'); return false;" href="#">Host @Html.DisplayNameFor(model => model.NavLicHost.Name)</a>
            </th>
            <th>
                <a onclick="LicToolSortPage('NavLicense.NavLicServer.Name'); return false;" href="#">Server @Html.DisplayNameFor(model => model.NavLicense.NavLicServer.Name)</a>
            </th>
            <th>
                <a onclick="LicToolSortPage('NavLicense.FeatureName'); return false;" href="#">@Html.DisplayNameFor(model => model.NavLicense.FeatureName)</a>
            </th>
            <th>
                <a onclick="LicToolSortPage('State'); return false;" href="#">@Html.DisplayNameFor(model => model.State)</a>
            </th>
            <th>
                <a onclick="LicToolSortPage('Version'); return false;" href="#">@Html.DisplayNameFor(model => model.Version)</a>
            </th>
            <th>
                <a onclick="LicToolSortPage('Quantity'); return false;" href="#">@Html.DisplayNameFor(model => model.Quantity)</a>
            </th>
            <th class="noprint"></th>
        </tr>
        <tr class="noprint">
            <td>
                @Html.SearchEditorFor(model => model.EndDate)
            </td>
            <td>
                @Html.SearchEditorFor(model => model.StartDate)
            </td>
            <td>
                @Html.SearchEditorFor(model => model.NavLicUser.Name)
            </td>
            <td>
                @Html.SearchEditorFor(model => model.NavLicHost.Name)
            </td>
            <td>
                @Html.SearchDropDownListFor(model => model.SelectedLicServer, (SelectList)ViewBag.AllLicServers, "", new { })
            </td>
            <td>
                @Html.SearchEditorFor(model => model.NavLicense.FeatureName)
            </td>
            <td>
                @Html.SearchDropDownListFor(model => model.State, (SelectList)ViewBag.AllStates, "", new { })
            </td>
            <td>
                @Html.SearchEditorFor(model => model.Version)
            </td>
            <td>
                @Html.SearchEditorFor(model => model.Quantity)
            </td>
            <td class="noprint">
                <input type="submit" value="@LicenseTool.ResourceLibrary.Common.Search" />
            </td>
        </tr>

        @foreach (LicenseTool.ClassLibrary.LicenseUsage item in ViewBag.ShownItems)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.ActionLink(item.NavLicUser.Name, "Index", "LicUser", new { userId = item.LicUser }, new { })
                </td>
                <td>
                    @Html.ActionLink(item.NavLicHost.Name, "Index", "LicHost", new { hostId = item.LicHost }, new { })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NavLicense.NavLicServer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NavLicense.FeatureName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Version)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td class="noprint">
                    @Html.ActionLinkWithImage("", "Edit", new { id = item.Id }, "~/Images/edit.png", LicenseTool.ResourceLibrary.Common.Edit, new { @width = "32", @height = "32" })
                    @Html.ActionLinkWithImage("", "Details", new { id = item.Id }, "~/Images/details.png", LicenseTool.ResourceLibrary.Common.Details, new { @width = "32", @height = "32" })
                    @Html.ActionLinkWithImage("", "Delete", new { id = item.Id }, "~/Images/delete.png", LicenseTool.ResourceLibrary.Common.Delete, new { @width = "32", @height = "32" })
                    @Html.ActionLinkWithImage("", "Index", "LicUser", new { userId = item.LicUser }, null, "~/Images/user.png", LicenseTool.ResourceLibrary.Model.Users, new { @width = "32", @height = "32" })
                    @Html.ActionLinkWithImage("", "Index", "LicHost", new { hostId = item.LicHost }, null, "~/Images/computer.png", LicenseTool.ResourceLibrary.Model.Hosts, new { @width = "32", @height = "32" })
                </td>
            </tr>
        }

    </table>
    @Html.Partial("~/Views/Shared/Paging.cshtml", Model);
}

<div class="content-group noprint">
    @Html.ActionLinkWithImage(LicenseTool.ResourceLibrary.Common.CreateNew, "Create", "~/Images/add.png", LicenseTool.ResourceLibrary.Common.CreateNew, new { @width = "32", @height = "32" })
</div>

@section Scripts {
    @Html.Partial("~/Views/Shared/Sorting.cshtml", Model)
    @Scripts.Render("~/bundles/jqueryui")
    @Html.Partial("~/Views/Shared/Tooltip.cshtml")
}