LicenseTool.WebApplication/Controllers/LicHostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LicenseTool.ClassLibrary;
using LicenseTool.WebApplication.Models;

namespace LicenseTool.WebApplication.Controllers
{

    /// <summary>
    /// Controller for the LicHost entity
    /// </summary>
    public class LicHostController : BaseController
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger
            (System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private ILicenseToolContext db = null;

        /// <summary>
        /// Constructor initializing the instance
        /// </summary>
        public LicHostController()
        {
            if (log.IsDebugEnabled) log.Debug("LicHostController");

            this.db = new LicenseToolDatabaseEntities();

            if (log.IsDebugEnabled) log.Debug("LicHostController Done");
        }

        /// <summary>
        /// Constructor initializing the instance
        /// </summary>
        /// <param name="db">The databse context to be used</param>
        public LicHostController(ILicenseToolContext db)
        {
            if (log.IsDebugEnabled) log.Debug("LicHostController");

            this.db = db;

            if (log.IsDebugEnabled) log.Debug("LicHostController Done");
        }

        /// <summary>
        /// Shows the list of all entities and passes it to <see cref="Index(LicHostSearchModel)"/>
        /// </summary>
        /// <param name="licenseId">The id of the License the index has to be filtered</param>
        /// <param name="serverId">The id of the LicServer the index has to be filtered</param>
        /// <param name="hostId">The id of the LicHost the index has to be filtered</param>
        /// <param name="userId">The id of the LicUser the index has to be filtered</param>
        /// <returns>The view result</returns>
        public ActionResult Index(int licenseId = 0, int serverId = 0, int hostId = 0, int userId = 0)
        {
            if (log.IsDebugEnabled) log.Debug("Index");

            LicHostSearchModel search = new LicHostSearchModel();
            search.SelectedLicense = licenseId;
            search.SelectedLicServer = serverId;
            search.SelectedLicHost = hostId;
            search.SelectedLicUser = userId;
            search.SortColumn = "Name";
            if (licenseId > 0)
            {
                License lic = db.License.FirstOrDefault(l => l.Id == licenseId);
                if (lic != null) search.SelectedLicServer = lic.LicServer;
            }

            if (log.IsDebugEnabled) log.Debug("Index Done");
            return Index(search);
        }

        /// <summary>
        /// Shows the list of all entities
        /// </summary>
        /// <param name="search">The search model to be applied</param>
        /// <returns>The view result</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LicHostSearchModel search)
        {
            if (log.IsDebugEnabled) log.Debug("Index");

            List<LicServer> servers = new List<LicServer>(db.LicServer.OrderBy(s => s.Name));
            IQueryable<LicHost> foundItems = null;
            if (search.SelectedLicServer == 0)
            {
                SelectList lst = new SelectList(servers, "Id", "Name");
                ViewBag.AllLicServers = lst;
                List<License> licenses = new List<License>();
                ViewBag.AllLicenses = new SelectList(licenses, "Id", "FeatureName");
                foundItems = db.LicHost;
            }
            else
            {
                SelectList lst = new SelectList(servers, "Id", "Name", search.SelectedLicServer);
                ViewBag.AllLicServers = lst;
                List<License> licenses = new List<License>(db.License.Where(l => l.LicServer == search.SelectedLicServer).OrderBy(s => s.FeatureName));
                if (search.SelectedLicense == 0)
                {
                    ViewBag.AllLicenses = new SelectList(licenses, "Id", "FeatureName");
                    foundItems = db.LicHost.Where(h => h.NavLicenseUsage.Any(u => u.NavLicense.NavLicServer.Id == search.SelectedLicServer));
                }
                else
                {
                    ViewBag.AllLicenses = new SelectList(licenses, "Id", "FeatureName", search.SelectedLicense);
                    foundItems = db.LicHost.Where(h => h.NavLicenseUsage.Any(u => u.NavLicense.Id == search.SelectedLicense));
                }
            }
            if (search.SelectedLicUser > 0)
            {
                foundItems = foundItems.Where(l => l.NavLicenseUsage.Any(u => u.LicUser == search.SelectedLicUser && u.LicHost == l.Id));
            }
            if (!string.IsNullOrEmpty(search.Name))
            {
                string[] tsts = search.Name.ToLower().Trim(new char[] { '*' }).Split(new char[] { '*' });
                foreach (string tst in tsts)
                    foundItems = foundItems.Where(l => l.Name.ToLower().Contains(tst));
            }
            if (search.SelectedLicHost > 0)
            {
                foundItems = foundItems.Where(h => h.Id == search.SelectedLicHost);
            }
            search.MaxItems = foundItems.Count();
            search.PageSize = Helpers.GetPageSize();
            foundItems = foundItems.Distinct();
            if (search.SortColumn == "Name")
            {
                if (search.SortDirection == 0)
                    foundItems = foundItems.OrderBy(s => s.Name);
                else
                    foundItems = foundItems.OrderByDescending(s => s.Name);
            }
            ViewBag.ShownItems = foundItems.Skip(search.PagingStartIndex * Helpers.GetPageSize())
                .Take(Helpers.GetPageSize()).ToList();

            if (log.IsDebugEnabled) log.Debug("Index Done");
            return View(search);
        }

        /// <summary>
        /// Shows the details of an entity
        /// </summary>
        /// <param name="id">The id of the entity to be shown</param>
        /// <returns>The view result if entity has been found</returns>
        /// <remarks>The method redirects to <see cref="HomeController.Error"/> if the entity with given id is not found</remarks>
        public ActionResult Details(int id = 0)
        {
            if (log.IsDebugEnabled) log.Debug("Details");

            LicHost lichost = db.LicHost.Find(id);
            if (lichost == null)
            {
                if (log.IsDebugEnabled) log.Debug("Details HttpNotFound Done");
                return RedirectToAction("Error", "Home", new { id = "404", aspxerrorpath = Request.Url.AbsolutePath });
            }

            if (log.IsDebugEnabled) log.Debug("Details Done");
            return View(lichost);
        }

        /// <summary>
        /// Shows the create new entity page
        /// </summary>
        /// <returns>The view result</returns>
        public ActionResult Create()
        {
            if (log.IsDebugEnabled) log.Debug("Create");

            if (log.IsDebugEnabled) log.Debug("Create Done");
            return View();
        }

        /// <summary>
        /// Post to create the new entity
        /// </summary>
        /// <param name="lichost">The entity to be created and stored in database</param>
        /// <returns>The view result if anything is wrong</returns>
        /// <remarks>Redirects to <see cref="Index(int,int,int,int)"/> if creation was succesfull</remarks>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LicHost lichost)
        {
            if (log.IsDebugEnabled) log.Debug("Create");

            if (ModelState.IsValid)
            {
                db.LicHost.Add(lichost);
                db.SaveChanges();

                if (log.IsDebugEnabled) log.Debug("Create RedirectToAction Done");
                return RedirectToAction("Index");
            }

            if (log.IsDebugEnabled) log.Debug("Create Done");
            return View(lichost);
        }

        /// <summary>
        /// Shows the edit page for an entity
        /// </summary>
        /// <param name="id">The id of the entity to be edited</param>
        /// <returns>The view result if entity has been found</returns>
        /// <remarks>The method redirects to <see cref="HomeController.Error"/> if the entity with given id is not found</remarks>
        public ActionResult Edit(int id = 0)
        {
            if (log.IsDebugEnabled) log.Debug("Edit");

            LicHost lichost = db.LicHost.Find(id);
            if (lichost == null)
            {
                if (log.IsDebugEnabled) log.Debug("Edit HttpNotFound Done");
                return RedirectToAction("Error", "Home", new { id = "404", aspxerrorpath = Request.Url.AbsolutePath });
            }

            if (log.IsDebugEnabled) log.Debug("Edit Done");
            return View(lichost);
        }

        /// <summary>
        /// Post to edit the new entity
        /// </summary>
        /// <param name="lichost">The entity to be changed and stored in database</param>
        /// <returns>The view result if anything is wrong</returns>
        /// <remarks>Redirects to <see cref="Index(int,int,int,int)"/> if change was succesfull</remarks>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LicHost lichost)
        {
            if (log.IsDebugEnabled) log.Debug("Edit");

            if (ModelState.IsValid)
            {
                db.SetModified(lichost);
                db.SaveChanges();

                if (log.IsDebugEnabled) log.Debug("Edit RedirectToAction Done");
                return RedirectToAction("Index");
            }

            if (log.IsDebugEnabled) log.Debug("Edit Done");
            return View(lichost);
        }

        /// <summary>
        /// Shows the delete page for an entity

LicenseTool.WebApplication/Views/LicHost/Create.cshtml
@model LicenseTool.ClassLibrary.LicHost

@{
    ViewBag.Title = @LicenseTool.ResourceLibrary.Common.Create;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><img src="~/Images/computer.png" alt="@ViewBag.Title" />@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>@LicenseTool.ResourceLibrary.Model.LicHost</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="@LicenseTool.ResourceLibrary.Common.Create" />
        </p>
    </fieldset>
}

<div>
    @Html.Partial("~/Views/Shared/BackToList.cshtml")
</div>

@section Scripts {
    @Html.Partial("~/Views/Shared/Validation.cshtml")
}

LicenseTool.WebApplication/Views/LicHost/Delete.cshtml
@model LicenseTool.ClassLibrary.LicHost

@{
    ViewBag.Title = @LicenseTool.ResourceLibrary.Common.Delete;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><img src="~/Images/computer.png" alt="@ViewBag.Title" />@ViewBag.Title</h2>

<h3>@LicenseTool.ResourceLibrary.Common.AreYouSureDelete</h3>
<fieldset>
    <legend>@LicenseTool.ResourceLibrary.Model.LicHost</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="@LicenseTool.ResourceLibrary.Common.Delete" /> |
        @Html.Partial("~/Views/Shared/BackToList.cshtml")
    </p>
}

LicenseTool.WebApplication/Views/LicHost/Details.cshtml
@model LicenseTool.ClassLibrary.LicHost

@{
    ViewBag.Title = @LicenseTool.ResourceLibrary.Common.Details;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><img src="~/Images/computer.png" alt="@ViewBag.Title" />@ViewBag.Title</h2>

<fieldset>
    <legend>@LicenseTool.ResourceLibrary.Model.LicHost</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLinkWithImage("", "Edit", new { id = Model.Id }, "~/Images/edit.png", LicenseTool.ResourceLibrary.Common.Edit, new { @width = "32", @height = "32", @class = "noprint" })
    @Html.Partial("~/Views/Shared/BackToList.cshtml")
</p>

LicenseTool.WebApplication/Views/LicHost/Edit.cshtml
@model LicenseTool.ClassLibrary.LicHost

@{
    ViewBag.Title = @LicenseTool.ResourceLibrary.Common.Edit;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><img src="~/Images/computer.png" alt="@ViewBag.Title" />@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>@LicenseTool.ResourceLibrary.Model.LicHost</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="@LicenseTool.ResourceLibrary.Common.Save" />
        </p>
    </fieldset>
}

<div>
    @Html.Partial("~/Views/Shared/BackToList.cshtml")
</div>

@section Scripts {
    @Html.Partial("~/Views/Shared/Validation.cshtml")
}

LicenseTool.WebApplication/Views/LicHost/Index.cshtml
@model LicenseTool.WebApplication.Models.LicHostSearchModel

@{
    ViewBag.Title = LicenseTool.ResourceLibrary.Model.Hosts;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><img src="~/Images/computer.png" alt="@ViewBag.Title" />@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "LicHost"))
{
    @Html.AntiForgeryToken()
    <p>
    <p>
        Search hosts using license server:<br />
        @Html.DropDownListFor(model => model.SelectedLicServer, (SelectList)ViewBag.AllLicServers, "", new { })
    </p>
    <p>
        Search hosts using license of given license server:<br />
        @Html.DropDownListFor(model => model.SelectedLicense, (SelectList)ViewBag.AllLicenses, "", new { })
    </p>
    @Html.HiddenFor(model => model.SelectedLicHost)
    @Html.HiddenFor(model => model.SelectedLicUser)
    @Html.HiddenFor(model => model.PagingStartIndex)
    @Html.HiddenFor(model => model.SortColumn)
    @Html.HiddenFor(model => model.SortDirection)
    <input type="submit" value="@LicenseTool.ResourceLibrary.Common.Search" />
    </p>
    <p>
    </p>
    <table>
        <tr>
            <th>
                <a onclick="LicToolSortPage('Name'); return false;" href="#">@Html.DisplayNameFor(model => model.Name)</a>
            </th>
            <th class="noprint"></th>
        </tr>
        <tr class="noprint">
            <td>
                @Html.SearchEditorFor(model => model.Name)
            </td>
            <td class="noprint">
                <input type="submit" value="@LicenseTool.ResourceLibrary.Common.Search" />
            </td>
        </tr>

        @foreach (LicenseTool.ClassLibrary.LicHost item in ViewBag.ShownItems)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="noprint">
                    @Html.ActionLinkWithImage("", "Edit", new { id = item.Id }, "~/Images/edit.png", LicenseTool.ResourceLibrary.Common.Edit, new { @width = "32", @height = "32" })
                    @Html.ActionLinkWithImage("", "Details", new { id = item.Id }, "~/Images/details.png", LicenseTool.ResourceLibrary.Common.Details, new { @width = "32", @height = "32" })
                    @Html.ActionLinkWithImage("", "Delete", new { id = item.Id }, "~/Images/delete.png", LicenseTool.ResourceLibrary.Common.Delete, new { @width = "32", @height = "32" })
                    @Html.ActionLinkWithImage("", "Index", "LicUser", new { hostId = item.Id }, null, "~/Images/user.png", LicenseTool.ResourceLibrary.Model.Users, new { @width = "32", @height = "32" })
                    @Html.ActionLinkWithImage("", "Index", "LicenseUsage", new { hostId = item.Id }, null, "~/Images/usage.png", LicenseTool.ResourceLibrary.Model.Usages, new { @width = "32", @height = "32" })
                </td>
            </tr>
        }

    </table>
    @Html.Partial("~/Views/Shared/Paging.cshtml", Model);
}

<div class="content-group noprint">
    @Html.ActionLinkWithImage(LicenseTool.ResourceLibrary.Common.CreateNew, "Create", "~/Images/add.png", LicenseTool.ResourceLibrary.Common.CreateNew, new { @width = "32", @height = "32" })
</div>

@section Scripts {
    @Html.Partial("~/Views/Shared/Sorting.cshtml", Model)
    @Scripts.Render("~/bundles/jqueryui")
    @Html.Partial("~/Views/Shared/Tooltip.cshtml")
}